### ISSUE TITLE
More URLs?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_French-GSD#11]
Is it possible to add a few more sentences with URLs to the training data?  This would make it easier for tools which automatically learn to process tokens to find the URLs.

https://github.com/stanfordnlp/stanza/issues/539

**Comment by bguil** [comment]
I don't think that it is a good practice to artificially change the data in a corpus in order to deal with a specific problem with a tool.
Anyway, we do not have any plan to change the data of UD_French-GSD in the next versions.

**Comment by dan-zeman** [comment]
Agreed with @bguil.

However, if you want to train a tool on data with more URLs (or more of any other specific phenomenon), you can create such artificial data yourself and distribute it with the tool.
