### ISSUE TITLE
Sentence with missing features

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_French-GSD#19]
The back half of this sentence is missing features.  I would expect some of the words would have features:

```
# sent_id = fr-ud-train_01057
30      :       :       PUNCT   _       _       31      punct   _       _
31      Maurice Maurice PROPN   _       _       26      appos   _       _
32      de      de      ADP     _       _       33      case    _       _
33      Londres Londres PROPN   _       _       31      nmod    _       SpaceAfter=No
34      ,       ,       PUNCT   _       _       35      punct   _       _
35      Robert  Robert  PROPN   _       _       31      conj    _       _
36      Blouet  Blouet  PROPN   _       _       35      flat:name       _       _
37      et      et      CCONJ   _       _       38      cc      _       _
38      Osmond  Osmond  PROPN   _       _       31      conj    _       _
39      de      de      ADP     _       _       40      case    _       _
40      Sées    Sées    PROPN   _       _       38      nmod    _       SpaceAfter=No
41      .       .       PUNCT   _       _       6       punct   _       _
```

**Comment by bguil** [comment]
This is usual form `PUNCT`, `ADP`, `CCONJ` not to have any features.

For `PROPN`, we could hope to have featues but it would require some work with external resources or manual annotation.  Currently:
 - about [88%](https://universal.grew.fr/?custom=6456192b147ee) of `PROPN` dot not have `Gender`
 - about [80%](https://universal.grew.fr/?custom=6456198f5e346) of `PROPN` dot not have `Number`.

All this explains this 12-token long senquence of absence of features.

**Comment by AngledLuffa** [comment]
Thanks for the fast responses!

> For PROPN, we could hope to have features but it would require some work with external resources or manual annotation.

I see.  Are the genders & numbers automatically produced, then, or are they annotated somewhere?  Normally I would think of "Robert" as a singular male, for example, but if those features are automatically produced, perhaps Robert Blouet isn't in that resource

**Comment by amir-zeldes** [comment]
If anyone wants to tackle this automatically, there are some useful lists with common names (celebrities, politicians etc.), for example:

https://github.com/amir-zeldes/xrenner/blob/master/xrenner/models/udx/names.tab
