### ISSUE TITLE
Suspicious lemma inconsistencies

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_French-GSD#23]
I was counting for lemmas where the same word might have two different possible lemmas (this can happen with a few verbs in English, for example).  Instead, I came across a few in the training data where I am suspicious the second form is actually a typo:

```
cours NOUN Counter({'cours': 162, 'cour': 2})
qu' PRON Counter({'que': 227, 'qui': 2})
jusqu' ADP Counter({'jusque': 203, "jusqu'": 1})
communes NOUN Counter({'commune': 52, 'commun': 1})
avoir VERB Counter({'avoir': 58, 'voir': 1})
toutes ADJ Counter({'tout': 80, 'toutes': 1})
fil NOUN Counter({'fil': 11, 'file': 1})
-ci ADV Counter({'ci': 5, '-ci': 1})
principales ADJ Counter({'principal': 19, 'principale': 1})
```

**Comment by bguil** [comment]
Thanks for the report.

> cours NOUN Counter({'cours': 162, 'cour': 2})

Correct: _cours_ (en: _course_/_class_) and _cour_ (en: _courtyard_) are two different nouns in French

> qu' PRON Counter({'que': 227, 'qui': 2})

This is correct: _qu'_ can be a elision of _que_ or _qui_

> jusqu' ADP Counter({'jusque': 203, "jusqu'": 1})

Fixed upsteam in SUD, will be in UD dev after data freeze

> communes NOUN Counter({'commune': 52, 'commun': 1})

Fixed

> avoir VERB Counter({'avoir': 58, 'voir': 1})

This is a typo in the source text (the feature `Typo=yes` is present on the token)

> toutes ADJ Counter({'tout': 80, 'toutes': 1})

Fixed

> fil NOUN Counter({'fil': 11, 'file': 1})

Typo in the source text

> -ci ADV Counter({'ci': 5, '-ci': 1})

Fixed

> principales ADJ Counter({'principal': 19, 'principale': 1})
Fixed

**Comment by AngledLuffa** [comment]
Excellent, thanks for the fast response!

If you don't mind me asking a French grammar question, for this one, this is correct and the word can be lemmatized in two different ways?

```
me PRON Counter({'moi': 40, 'soi': 8})
```

**Comment by dseddah** [comment]
re your "me" question. I guess when used with a reflexive verb (eg. se laver) it will be "se/soi" while as a clitic "il me manque" (I miss him) it will be moi
