### ISSUE TITLE
annotation of l'un(e), l'on

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/UD_French-GSD#3]
Hello,
I just have came across an annotation of the _l'un/l'une_ et _l'on_ for which I do not understand the motivation:
```
# sent_id = fr-ud-train_02563
...
5	l	le	DET	_	Definite=Def|Gender=Fem|Number=Sing|PronType=Art	6	det	_	_
6	église	église	NOUN	_	Gender=Fem|Number=Sing	10	nsubj	_	_
7	Saint-Martin	Saint-Martin	PROPN	_	_	6	appos	_	_
8	est	être	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	10	cop	_	_
9	l'	l'	PART	_	_	10	expl	_	SpaceAfter=No
10	une	un	PRON	_	Gender=Fem|Number=Sing	0	root	_	_
11-12	des	_	_	_	_	_	_	_	_
11	de	de	ADP	_	_	15	case	_	_
12	les	le	DET	_	Definite=Def|Gender=Fem|Number=Plur|PronType=Art	15	det	_	_
13	plus	plus	ADV	_	_	14	advmod	_	_
14	anciennes	ancien	ADJ	_	Gender=Fem|Number=Plur	15	amod	_	_
15	églises	église	NOUN	_	Gender=Fem|Number=Plur	10	nmod	_	_
```
why is the article (9 l') marked as PART (deprel `expl`) and not as DET with deprel `det`? 
Is it due the following pronoun? In this case I would expect _l'autre_ (in other sentences) being annotated in the same way.
The French-ParTUT and Sequoie treebanks use `l'  le  DET .... det` for all instances of _l'un(e)_ et _l'on_, so I wonder whether this is just a conversion error?

Best regards
Johannes

**Comment by dseddah** [comment]
Hi,
I’m pretty sure it’s a genuine mistake.

Best,
Djamé

**Comment by bguil** [comment]
Annotations changed in 51dc39e32cb6d0bcd3d15f0488cd3600ed88966a
