### ISSUE TITLE
modal verbs as heads

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/UD_French-GSD#5]
Hello,

a change which hase been introduced since v2.0 (I cannot remember exactly when) is the annotation of modal verbs (_pouvoir_, _devoir_, _falloir_). In version 2.0 they were annotated as `aux` with the main head as head, now the modals are head, and the main verb is attached as `xcomp` to the modal verb  (cf. sentence 20).

However, we have been annotating French (short) questions, and the fact that modals are heads of the main verbs has non-projective annotations as a consequence. For example _Dans quel pays pouvez-vous visiter les pyramides ?l_ («in which country can you visit the pyramides?»),  if we attach _country_ to the main verb (as `obl`) and not to _pouvoir_:

```
1	Dans	dans	ADP	ADP	_	3	case	0	_
2	quel	quel	DET	DET	Gender=Masc|Number=Sing	3	det	0	_
3	pays	pays	NOUN	NOUN	Gender=Masc|Number=Sing	6	obl	0	_
4	pouvez	pouvoir	AUX	AUXM	Mood=Ind|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin	0	root	0	_
5	-vous	vous	PRON	PERS_NOM	Number=Plur|Person=2|PronType=Prs	4	nsubj	0	_
6	visiter	visiter	VERB	INF	VerbForm=Inf	4	xcomp	0	_
7	les	les	DET	ART	Definite=Def|Gender=Fem|Number=Plur|PronType=Art	8	det	0	_
8	pyramides	pyramide	NOUN	NOUN	Gender=Masc|Number=Sing	6	amod	0	_
9	?	?	PUNCT	PUNCT	_	4	punct	0	_
```
What is your opinion to this ?

- accepting non-projectives (which are not that frequent in the French treebanks)
- attaching `obl` to the modal verb (_pouvoir_) in order to avoid non-projective annotations

Regards
Johannes

**Comment by martinpopel** [comment]
The decisions which verbs are modal (VerbType=Mod) and whether modal verbs are auxiliary (upos=AUX) is [language specific](http://universaldependencies.org/u/pos/AUX_.html).

> modal verbs (pouvoir, devoir, falloir). In version 2.0 they were annotated as aux with the main head as head, now the modals are head,

If this is the case, the [French AUX guidelines](http://universaldependencies.org/fr/pos/AUX_.html) should be updated. (The guidelines are still marked as UDv1, so it should be updated anyway. Now, I am not sure if the new documentation structure  expects each language to have a separate page about each UPOS, but the information should be somewhere.)

> accepting non-projectives (which are not that frequent in the French treebanks)

Non-projectivities are fully accepted in UD ([sometimes](https://github.com/UniversalDependencies/UD_Czech-PDT/issues/3) even preferred over the original-treebank projective-style annotation).
Even if you treat modals as auxiliaries, there is a wide range of phase verbs and complex-verb constructions, which will result in non-projectivities.
E.g. _Dans quel pays **préférez**-vous visiter les pyramides?_

**Comment by dan-zeman** [comment]
The per-tag documentation is optional. What is now mandatory (although still lacking in many languages) is one lang-spec documentation page (index.html in the language folder), following the template and the instructions at http://universaldependencies.org/contributing_language_specific.html. If you have additional pages for individual tags etc., you can link to them from the index page.

**Comment by bguil** [comment]
Most French treebanks now use the 3 auxiliaries *être*, *avoir* and *faire*.
