### ISSUE TITLE
Multiple word spans

### ISSUE THREAD

**Issue by Eugen2525** [UniversalDependencies/UD_French-GSD#8]
So when I use parser by https://github.com/tdozat/Parser-v2 which has succesfully passed the evaluation, I am getting an error on multi word spans if I evaluate by the official script http://universaldependencies.org/conll17/eval.zip . 
Example:
In the 2nd sentence of test set we have a sentence like:

1	On	on	PRON	_	Gender=Masc|Number=Sing|Person=3	2	nsubj	_	_
2	pourra	pouvoir	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin	0	root	_	_
3	toujours	toujours	ADV	_	_	2	advmod	_	_
4	parler	parler	VERB	_	VerbForm=Inf	2	xcomp	_	_
5	à	à	ADP	_	_	8	case	_	_
6	propos	propos	NOUN	_	Gender=Masc|Number=Sing	5	fixed	_	_
7	d'	de	ADP	_	_	5	fixed	_	SpaceAfter=No
8	Averroès	Averroès	PROPN	_	_	4	obl:mod	_	_
9	de	de	ADP	_	_	11	case	_	_
10	"	"	PUNCT	_	_	11	punct	_	SpaceAfter=No
11	décentrement	décentrement	NOUN	_	Gender=Masc|Number=Sing	4	obl:arg	_	_
12-13	du	_	_	_	_	_	_	_	_
12	de	de	ADP	_	_	14	case	_	_
13	le	le	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	14	det	_	_
14	Sujet	sujet	NOUN	_	Gender=Masc|Number=Sing	11	nmod	_	SpaceAfter=No
15	"	"	PUNCT	_	_	11	punct	_	SpaceAfter=No
16 . . PUNCT _ _ 2 punct _ _

where 12-13 is a token "du" which is decomposed into "de" and "le" and these two tokens should be parsed. Thus the output of the parser is:

1	On	on	PRON	_	_	4	nsubj	_	_
2	pourra	pouvoir	AUX	_	_	4	aux	_	_
3	toujours	toujours	ADV	_	_	4	advmod	_	_
4	parler	parler	VERB	_	_	0	root	_	_
5	à	à	ADP	_	_	6	case	_	_
6	propos	propos	NOUN	_	_	4	obl	_	_
7	d'	de	ADP	_	_	8	case	_	_
8	Averroès	Averroès	PROPN	_	_	6	nmod	_	_
9	de	de	ADP	_	_	11	case	_	_
10	"	"	PUNCT	_	_	11	punct	_	_
11	décentrement	décentrement	NOUN	_	_	6	nmod	_	_
12	de	de	ADP	_	_	14	case	_	_
13	le	le	DET	_	_	14	det	_	_
14	Sujet	sujet	NOUN	_	_	11	nmod	_	_
15	"	"	PUNCT	_	_	11	punct	_	_
16	.	.	PUNCT	_	_	4	punct	_	_

where we have the entry 12-13 missing and which is causing error for the evaluation script like below:

First 20 differing characters in gold file: 'uSujet".«Ilaétéla' and system file: 'eleSujet".«Ilaété'

So could this be dealt?

**Comment by jnivre** [comment]
This looks like a problem with the parser, rather than the UD resources, so I think you should contact the parser developer.

**Comment by dseddah** [comment]
Hi,
I think I recall this parser used udpipe for tokenization and word segmentation. You are not  supposed to parse already segmented input (de+le) and expect the parser to recover the contracted form (du).

If you want the full chain, it's probably better to use the last stanford python nlp they just released.

Djamé

**Comment by Eugen2525** [comment]
Thanks for your valuable comments, I think I can solve the issue with multi word spans.

Another issue came up however. The number of sentences of this french treebank in input UD pipe version and gold versions contain different amount of sentences as is found here:  https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-2184

For example the following sentence is a single sentence in UD pipe but two separate sentences in the gold file:
très bon accueil les chambres sont très agréables et spacieuses bon rapport qualité prix un café 17 euros !

So maybe this question is not to you but maybe just to document the issue.

Thanks

**Comment by dseddah** [comment]
Hi, you need to get back to the definition of the conll UD shared task 2017 and 2018.
It was about end to end parsing with no gold tokenization, morphology and segmentation provided.
It’s perfectly normal to have a mismatch at all levels between gold and predicted data, even if it was provided by udpipe.

Best,
Djamé
